# Setting up everything to work on the FHIR for Research website for Windows

1.  Go to github.com and sign up for an account, enable 2fa, get added to relevant repo(s)
2.  Go to quarto.org and go to "get started", and download quarto
3.  Install R using this website: <https://cran.r-project.org/bin/windows/base/>
4.  Install RStudio: <https://posit.co/download/rstudio-desktop/> should auto-populate with appropriate version for windows
5.  Install Git using this website: <https://git-scm.com/download/win>

-   Double check that you have Git installed by typing Git in terminal or command prompt. Doing so should produce options and recommendations for git commands

6.  SSL Issues---this may be an issue for MITRE-employees using ZScaler.

-   Download MITRE cert and save in home file
-   Paste the following in terminal, replacing <username> with your own:

```         
git config --global http.sslCAInfo
C:/Users/<username> /ca-certificates.crt
```

7.  Install Python for Windows:
    -   Open command prompt

    -   Type "Python" and hit enter

    -   Select install

    -   Paste equivalent to the below example with appropriate file path in terminal (cd \[file path to folder with project/project-name\]:

        ```         
        cd git/fhir-for-research
        python3 -m venv python_env
        ```
8.  Open RStudio

-   Load the project in RStudio
    -   Either navigate through the file navigator on the right if you have the project locally, or if you need to clone an existing, remote repository, use the instructions here: <https://happygitwithr.com/rstudio-git-github.html>
-   Copy/Paste the following command into Console if prompted with an error:

```         
renv::restore()
```

-   Windows users may need to install R Tools: <https://cran.r-project.org/bin/windows/Rtools/rtools43/files/rtools43-5550-5548.exe>
    -   After installing RTools, quit RStudio then reopen the app and open the project again
-   Copy/paste the following into Console if prompted:

```         
renv::snapshot()
```

9.  Install Jupyter using the instructions at <https://jupyter.org/install>

-   To check that Jupyter is installed correctly, copy/paste the following command into terminal or command prompt. It should launch Jupyter Notebook: `jupyter notebook`

-   Troubleshooting issues with Jupyter on Windows:

    -   Errors in RStudio or the command prompt indicating that Jupyter is not installed might mean the filepath for where Jupyter was installed needs to be added to PATH.
    -   Restarting the process by installing Anaconda may help but it shouldn't be necessary: <https://www.anaconda.com>
    -   Locate where Anaconda is saved if it was installed, or Jupyter itself if Anaconda was not. It might be in a similar destination to: `C:\\User\<username>\AppData\Local` or `C:\\User\<username>\AppData\Roaming`
    -   Copy the file path
    -   In System Settings, search for Environment Variables and select
    -   Select `Path` to edit
    -   Select `Add New` so the file path previously copied can be added
    -   Click `Ok` in three windows until the System Settings are closed
    -   Close and reopen the command prompt. Try to launch a Jupyter Note again with `jupyter notebook`

-   Resources that might be helpful:

    -   <https://jupyter-notebook.readthedocs.io/en/stable/troubleshooting.html>
    -   <https://stackoverflow.com/questions/48350692/jupyter-notebook-installation-issue-using-pip>
    -   <https://www.geeksforgeeks.org/how-to-setup-anaconda-path-to-environment-variable/>

10. Useful to know:

-   `quarto check` in the terminal or command prompt will return what components of Quarto have been installed properly and where there might be issues
