---
title: Introduction

roles:
  - Investigator
  - Research Leaders
  - Informaticist
  - Software Engineer
  - Clinician Scientist/Trainee

learning_objectives:
  - question: What characteristic of research suggests SMART on FHIR may be helpful?
    answer: Research that requires integration with an EHR may benefit from SMART on FHIR.
  - question: What has SMART on FHIR already been used for in published research?
    answer: SMART on FHIR has been used to integrate new CDS systems into EHRs, and integrate additional data sources like patient-reported outcomes into EHRs.
---

[SMART on FHIR](https://smarthealthit.org)[^1] was introduced in 2016 [@Mandel_Kreda_Mandl_Kohane_Ramoni_2016] "to enable medical applications to be written once and run unmodified across different healthcare IT systems".

[^1]: SMART stands for Substitutable Medical Applications and Reusable Technologies.

To enable "write once, run anywhere" applications, the [SMART on FHIR standards](http://docs.smarthealthit.org) leverage FHIR along with common web technology. Support for SMART on FHIR applications are currently included in many common EHRs, including those from [Cerner](https://fhir.cerner.com), [Epic](https://fhir.epic.com), and [MEDITECH](https://ehr.meditech.com/ehr-solutions/greenfield-workspace). Researchers have been successful in using their SMART on FHIR applications across multiple EHRs [@Wesley_2021], though additional work may be needed due to EHR- and institution-specific implementation differences.

## Research use cases

SMART on FHIR is primarily used for research that requires integration with an EHR. For example, researchers conducting a trial on a new clinical decision support (CDS) system can use SMART on FHIR to integrate their custom CDS tool directly into EHRs without modifying the EHR itself or requiring entirely separate versions for each EHR vendor. This approach has been used by @tarumi2021, who demonstrated an AI-driven CDS integrated with Epic via SMART on FHIR. @curran2020 prototyped a CDS system for chronic disease management using SMART on FHIR.

SMART on FHIR can also be used for adding new data to EHR workflows. For example, a patient-facing web application or smartphone app can be used to capture patient-reported outcomes data, and a SMART on FHIR application can make this data accessible from within the EHR [@Wesley_2021]. SMART on FHIR could also be used to integrate clinical information that is not natively supported by the EHR. For example, @watkins2020 discuss how genetic testing could be better-integrated with EHRs using SMART on FHIR and CDS Hooks (see below).

Bulk Data Access (see below) facilitate by SMART on FHIR may provide a new avenue for researchers to access population-scale data (compared to focusing a specific patient or patients). This could be especially useful for multi-institution collaborations that do not already use a shared common data model, especially if the necessary data are part of the widely implemented [US Core FHIR Implementation Guide](https://www.hl7.org/fhir/us/core/). However, Bulk Data Access is relatively new and has not yet appeared in peer-reviewed research publications.

The [SMART App Gallery](https://apps.smarthealthit.org/apps) lists a number of SMART on FHIR applications, which may provide additional ideas of how SMART on FHIR could be applied to research.

## Capabilities

SMART on FHIR pulls together a number of existing standards to provide a complete set of capabilities necessary to enable third-party application integration with EHRs. These include:

| Capability              | Approach                                                                                                                                                                                                           |
|:-----------------|:-----------------------------------------------------|
| Authorization           | The [OAuth 2](https://oauth.net/2/) web standard is to allow a third party SMART on FHIR application to access a specific set of data from an EHR.                                                                 |
| Authentication          | The [OpenID Connect](https://openid.net/connect/) web standard allows SMART on FHIR applications to tell the EHR who is running them (e.g., to allow a patient to access their own health data via SMART on FHIR). |
| Data models             | The standard set of [FHIR resources](https://www.hl7.org/fhir/resourcelist.html) are used to represent data. Additional customization can occur via FHIR profiles (see below).                                     |
| Profiles                | [US Core Data Profiles](https://www.hl7.org/fhir/us/core/) or other FHIR Implementation Guides can be used to provide additional customization on top of the standard FHIR resources.                              |
| Data access             | Once a third party application is authenticated and authorized, the standard [FHIR REST API](https://www.hl7.org/fhir/http.html) can be used to exchange data.                                                     |
| Data format             | Data are formatted using the standard FHIR [JSON](https://www.hl7.org/fhir/json.html) or [XML](https://www.hl7.org/fhir/xml.html) formats.                                                                         |
| EHR UI integration      | Third party applications can be launched from within an EHR using [SMART App Launch](http://hl7.org/fhir/smart-app-launch/index.html).                                                                             |
| EHR backend integration | Third party applications can integrate with an EHR without requiring a manual EHR user interaction to launch them using [SMART Backend Services](https://hl7.org/fhir/uv/bulkdata/authorization/index.html).       |

: SMART on FHIR capabilities, adapted from @Mandel_Kreda_Mandl_Kohane_Ramoni_2016. {tbl-colwidths="\[25,75\]"}

## Related technology

### Bulk Data Access

The [Bulk Data Access standard](http://hl7.org/fhir/uv/bulkdata/) provides a mechanism for retrieving large volumes of data across a patient population from an EHR. It was first released in 2019, and v2 was released in November 2022.

An example use case from the [standard](http://hl7.org/fhir/uv/bulkdata/) is:

> A health system may want to periodically retrieve updated clinical data from an EHR to a research database

This standard has been [adopted](https://docs.google.com/presentation/d/14ZHmam9hwz6-SsCG1YqUIQnJ56bvSqEatebltgEVR6c/edit#slide=id.g8c17644f87_23_1146) by Allscripts, Athena Health, Cerner, and Epic as of October 2022. In January 2023, [ONC announced its support for this standard](https://www.healthit.gov/buzz-blog/health-it/onc-supports-adoption-and-implementation-of-bulk-data-apis).

This standard is part of the [SMART ecosystem](https://smarthealthit.org/), and SMART on FHIR can be used to authenticate and authorize applications that retrieve bulk data automatically.

::: {.callout-tip appearance="simple"}
For more information, see [this overview presentation](https://docs.google.com/presentation/d/14ZHmam9hwz6-SsCG1YqUIQnJ56bvSqEatebltgEVR6c/edit?usp=sharing) and the [HL7 specification](http://hl7.org/fhir/uv/bulkdata/).
:::

### CDS Hooks

[CDS Hooks](https://cds-hooks.org) is an [HL7 standard](https://cds-hooks.hl7.org/) that can be used to support SMART on FHIR application integration with EHRs. [v2](https://cds-hooks.hl7.org/2.0/) of the CDS Hooks specification was released in August 2022.

CDS Hooks provides a mechanism for an action in an EHR to trigger an action in a third-party application. @thiess2022 writes:

> To make CDS accessible when it is needed, the standard defines several hooks that occur through clinicians interacting with the EHR. For example, the *patient-view* hook is triggered when the patient record is opened, or the *order-select* hook is triggered when the prescriber selects an order (e.g., medication or procedure).

The standard includes mechanisms for the third-party application to receive information relevant to the context of the hook, like data on the patient being viewed. The application can then send information back to the EHR. @thiess2022 continues:

> The CDS Hooks service provides a response in the form of a "Card" that is displayed inside the EHR. There are three types of cards: (i) information cards provide patient-specific information, such as an assessment or reference information; (ii) suggestion cards provide a recommended action (e.g., an order) in a FHIR resource; and (iii) app cards provide a link to launch a SMART on FHIR app.

#### Further reading

-   @morgan2022 demonstrate that CDS Hooks can increase utilization of SMART on FHIR applications.

-   @strasberg2021 describes additional background information on how CDS Hooks function.

-   @thiess2022 provides more details on how CDS Hooks can be integrated with an EHR and a SMART on FHIR application.

## Implementation considerations

If you have a research use case that is a good fit with SMART on FHIR, you will likely need to work with a software engineer and your institution's IT experts to develop an approach and investigate integration with the relevant EHR(s).

SMART on FHIR applications that integrate with an EHR's user interface via SMART App Launch are often built as web applications. While any web software engineer will likely have experience with the underlying common web technology (e.g., JSON, REST, OAuth, etc.), they may not have experience with health data or FHIR. Though FHIR is based on common web technology, there is still a learning curve to understand the specification and ecosystem. There also may be EHR implementation-specific complexity with integration, including getting administrative approval. If your institution has staff with experience integration SMART on FHIR applications, it will likely be worthwhile to consult with them early when developing your research approach.

For "backend applications" that run without being triggered by user input in an EHR, including applications that use Bulk Data Access, you will likely need to work with a software engineer familiar with working with large clinical datasets and FHIR. Integration with the EHR is likely less complex than with a UI-launched SMART on FHIR application, but there may still be EHR implementation-specific complexity including administrative approval.

Security and privacy should also be considered early in the process of developing your research approach. While there is nothing inherently insecure about SMART on FHIR, steps should be taken to ensure proper data storage and access as with any software handling potentially sensitive data. In addition to IRB approval, you may need approval or review from others (e.g., Privacy or Information Security). If your institution has not worked with SMART on FHIR before, there may not be a well-defined process for getting the appropriate reviews and approvals in place.

Please see [SMART on FHIR Technical Details](smart-on-fhir-tech.qmd) for more technical implementation on using SMART on FHIR and related standards.
