---
title: "Terminology and FHIR"

area:
  name: Overview
topic:
  name: FHIR for Research

roles:
  - Investigator
  - Informaticist
  - Software Engineer
  - Clinician Scientist/Trainee

learning_objectives:
  - question: What key role does standardized terminology play in enabling health data interoperability?
    answer: Standardized terminology is essential in allowing data to move across systems while maintaining shared meaning.
  - question: What are some use cases for terminology in research?
    answer: Several are discussed above, including enabling automatic cohort building and more efficiently aggregating data across different systems or institutions.
  - question: What are the key FHIR resources related to terminology?
    answer: CodeSystems define a specific terminology and its concepts; ValueSets identify a subset of relevant concepts from one or more code systems; ConceptMaps map one set of concepts onto another.
---

Terminology is a critical component of interoperability of clinical data, allowing "the ability to represent concepts in an unambiguous manner between a sender and receiver of information" [@himss_terminology].

Terminology in health informatics fundamentally consists of mappings between **concepts** and **codes**, defined within a **code system**.

::: callout-note
## Definitions

Concept

:   A mental representation of a real or abstract thing.

    For example, a disease state (like "type 2 diabetes") or medical procedure (like "bilateral hip replacement") are both concepts.

Code

:   A series of letters, numbers, or symbols assigned a concept for identification or classification.

    Codes are typically machine-readable, allowing for unambiguous identification of the related concept.

    For example, the [ICD-11](https://icd.who.int/en) code `EJ40` refers to the concept "[Sunburn](https://icd.who.int/browse11/l-m/en#/http%3A%2F%2Fid.who.int%2Ficd%2Fentity%2F318744822)".

Code system

:   A predefined, limited list of concepts and their corresponding codes. Code systems often also include metadata like relationships between concepts or more detailed human-readable descriptions.

    Code systems may also be known as "coding systems" or "controlled vocabularies".

    ICD-11, mentioned above, is an example of a code system. Other examples are discussed below.
:::

The same concept may appear in multiple code systems, necessitating mappings between these concepts.[^1]

[^1]: The [ConceptMap FHIR resource](https://www.hl7.org/fhir/conceptmap.html) supports mapping concepts across code systems. See below for details.

## Terminology's importance for research

Using standard terminologies allows researchers to access, exchange, organize, and utilize health data in a consistent and reliable way.

For example, using a standardized terminology to identify conditions in a problem list allows for automated cohort building based on the presence or absence of a specific set of conditions.

Standardized terminology also allows for combining data from multiple different systems and institutions, though care must still be taken to ensure concept meanings are implemented consistently. [Semantic interoperability](https://en.wikipedia.org/wiki/Semantic_interoperability) is the term used by informaticists to describe systems that can exchange data with "unambiguous, shared meaning."

FHIR supports defining code systems, mapping between them, and "binding" a FHIR data element to a specific subset of concepts from selected code systems.

## Common health-related code systems

Health data often contains codes from the following code systems:

-   [LOINC](https://loinc.org/) (Logical Observation Identifiers Names and Codes)

-   [SNOMED CT](https://www.snomed.org/) (Systematized Nomenclature of Medicine--Clinical Terms)

-   [ICD](https://www.who.int/standards/classifications/classification-of-diseases) (International Statistical Classification of Diseases and Related Health Problems)

-   [RxNorm](https://www.nlm.nih.gov/research/umls/rxnorm/index.html) (Medical prescription Normalized)

-   [CVX](https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=cvx) (Vaccine administered)

Below are details about each of these code systems. Additionally, [HIMSS provides a longer list of common code systems](https://www.himss.org/terminology-standards).

### LOINC

LOINC is a common language for identifying health measurements, observations, and documents. It often represents the "question" that an observation asks, with other standards (such as SNOMED CT; described next) representing the "answer." The Regenstrief Institute, which maintains LOINC, calls it "the global lingua franca for identifying tests and observations." [@loinc_get_started]

#### Structure

A LOINC code distinguishes a given observation (test ordered, survey question, or clinical document) across six dimensions known as **Parts** [@loinc_term_basics]. The table below defines each Part, and provides an example using the LOINC concept identified by the code [`806-0`](https://loinc.org/806-0), which represents *a manual count of white blood cells in cerebral spinal fluid specimen*.

| LOINC Part          | Definition                                                                                                                                                 | Example                        |
|---------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------|
| Component (Analyte) | The substance or entity being measured                                                                                                                     | Leukocytes (white blood cells) |
| Property            | The characteristic or attribute of the analyte                                                                                                             | NCnc (Number concentration)    |
| Time                | The interval of time over which an observation was made                                                                                                    | Pt (Point in time)             |
| System (Specimen)   | The specimen or thing upon which the observation was made                                                                                                  | CSF (Cerebral spinal fluid)    |
| Scale               | How the observation value is quantified or expressed: quantitative, ordinal, nominal                                                                       | Qn (Quantitative)              |
| Method              | (Optional) A high-level classification of how the observation was made. Only needed when the technique affects the clinical interpretation of the results. | Manual Count                   |

There are three different human-readable descriptions that LOINC creates for each of its concepts concept [@loinc_term_basics]:

| Text Label (Name)          | Example for [`806-0`](https://loinc.org/806-0) (test above)      |
|----------------------------|------------------------------------------------------------------|
| Fully-Specified Name (FSN) | Leukocytes: NCnc: Pt: CSF: Qn: Manual count                      |
| Long Common Name           | Leukocytes \[#/volume\] in Cerebral spinal fluid by Manual count |
| Short Name                 | WBC \# CSF Manual                                                |

### SNOMED CT

SNOMED CT is a clinical terminology standard that is developed by **SNOMED International**. It can be viewed as the "answer" for a test or measurement (where LOINC would often specify the "question" answered by a SNOMED concept). [SNOMED International further details the utility of SNOMED CT](https://www.snomed.org/five-step-briefing) as follows:

> SNOMED CT:
>
> -   Is the most comprehensive, multilingual clinical healthcare terminology in the world
> -   Is a resource with comprehensive, scientifically validated clinical content
> -   Enables consistent representation of clinical content in electronic health records
> -   Is mapped to other international standards
> -   Is in use in more than eighty countries

#### Structure

SNOMED CT is comprised of [@snomed]:

-   **Concepts**: Unique clinical meaning that is referenced with a unique computer readable numeric identifier. Can have multiple descriptions.

-   **Descriptions**: Human readable phrases that describe a concept (what a doctor would read).

-   **Relationships**: Correlation between related concepts, i.e. "synonyms." Provides computer readable definitions of concepts and allow for data to be searched for in a variety of ways.

    There are two main types of relationships in SNOMED CT:

    -   **Hierarchical relationships** establish each SNOMED CT concept as a child of a more general concept. Each concept in SNOMED CT has at least one hierarchical relationship. For example, `840533007` (SARS-CoV-2) has an `is a` relationship with its parent, `415360003` (SARS coronavirus), which in turn `is a` `868196001` (Subgenus Sarbecovirus).

    -   **Attribute relationships** define non-hierarchical relationships between two concepts; each concept can have as many attribute relationships as needed. For example, `399150003` (PCR test for SARS) has a `Component` relationship with `415360003` (SARS coronavirus).[^2]

[^2]: SNOMED CT relationship types are defined by SNOMED concepts. In this case, "Component" is represented by the [SNOMED CT code `246093002`](https://browser.ihtsdotools.org/?perspective=full&conceptId1=246093002&edition=MAIN/2023-02-28&release=&languages=en) .

Below is an example how SNOMED might represent a condition (acute post-streptococcal glomerulenephritis) and its associated relationships: <!--# FIX for Blake to do: Add citation for diagram: adapted from "Georgia Tech Online Health Informatics MS course video" —MM 3/23/23 11:50 AM -->

```{mermaid}
flowchart BT
    A{{SNOMED - CT Concept}}
    B[Clinical Finding\n404684003]
    C[Body Structure\n123037004]
    D[Both Kidneys\n17373004]
    E[Acute post-streptococcal glomerulonephritis\n68544003]
    F[Organism\n410607006]
    G[Beta-hemolytic Streptococcus, group A\n413643004]

    B --> |is a|A
    F --> |is a|A
    F --> |is a|B
    G --> |is a|F
    G --> |Causative agent|E
    E --> |Finding site|D
    D --> |is a|C
    C --> |is a|B
    C --> |is a|A
```

### ICD

[ICD](https://www.who.int/standards/classifications/classification-of-diseases) is a medical classification list that contains codes for diseases, signs and symptoms, abnormal findings, complaints, social circumstances, and external causes of injury or diseases. [The WHO, who publishes ICD, writes](https://www.who.int/standards/classifications/classification-of-diseases):

> Clinical terms coded with ICD are the main basis for health recording and statistics on disease in primary, secondary and tertiary care, as well as on cause of death certificates. These data and statistics support payment systems, service planning, administration of quality and safety, and health services research. Diagnostic guidance linked to categories of ICD also standardizes data collection and enables large scale research.

ICD-10 is currently widely used, having replaced ICD-9 in the US in the 2010s. ICD-11 is the latest version of ICD, with active use beginning in January 2022.

#### ICD-10 structure

An ICD-10 code can range between 3 and 7 alphanumeric characters and has three major parts [@icd_10]:

1.  **Category**: A three character code that always begins with one letter that is followed by two numbers. This code describes the general type of injury or disease.
2.  **Subclassification** (optional): To further specify an injury or disease, the three-character alphanumeric category code can be followed by a decimal point and up to three different levels of classification to further explain the cause, manifestation, location, severity, and type of injury or disease. This code section can be up to 3 numeric characters, with each added character adding more specificity.
3.  **Extension** (optional): This final code section is one of three letters that describe the type of encounter a given injury or disease. It will always be the 7th character and directly follows the subclassification numbers, not requiring a decimal point to separate it. It can either be A (initial encounter), D (subsequent encounter), or S (sequila).

::: {.callout-caution collapse="true"}
## Expand to view ICD-10 categories

| Range    | Topic                                                                                               |
|----------|-----------------------------------------------------------------------------------------------------|
| A00-B99  | Certain infections and parasitic diseases                                                           |
| C00-D49  | Neoplasms                                                                                           |
| D50-D89  | Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism |
| E00-E89  | Endocrine, nutritional and metabolic diseases                                                       |
| F01-F99  | Mental, Behavioral and Neurodevelopmental disorders                                                 |
| G00-G99  | Diseases of the nervous system                                                                      |
| H00-H59  | Diseases of the eye and adnexa                                                                      |
| H60-H95  | Diseases of the ear and mastoid process                                                             |
| I00-I99  | Diseases of the circulatory system                                                                  |
| J00-J99  | Diseases of the respiratory system                                                                  |
| K00-K95  | Diseases of the digestive system                                                                    |
| L00-L99  | Diseases of the skin and subcutaneous tissue                                                        |
| M00-M99  | Diseases of the musculoskeletal system and connective tissue                                        |
| N00-N99  | Diseases of the genitourinary system                                                                |
| O00- O9A | Pregnancy, childbirth, and puerperium                                                               |
| P00-P96  | Certain conditions originating in the perinatal period                                              |
| Q00-Q99  | Congenital malformations, deformations and chromosomal abnormalities                                |
| R00-R99  | Symptoms, signs, and abnormal clinical laboratory findings, not elsewhere classified                |
| S00-T88  | Injury, poisoning, and certain other consequences of external causes                                |
| V00-Y99  | External causes of morbidity                                                                        |
| Z00-Z99  | Factors influencing health status and contact with health services                                  |
:::

Below is an example of different levels of specificity for an ICD-10 code [@icd_10]. The injury is a *closed fracture of distal phalanx of right index finger*.

-   **`S62` -- fracture at wrist and hand level**

    -   `S62.0` -- fracture at navicular \[scaphoid\] bone of wrist

    -   ...

    -   `S62.5` -- fracture of thumb

    -   **`S62.6` -- fracture of other and unspecified finger(s)**

        -   `S62.60` -- fracture of unspecified phalanx of finger

        -   `S62.61` -- displaced fracture of proximal phalanx of finger

        -   ...

        -   **`S62.63` -- displaced fracture of distal phalanx of finger**

            -   **`S62.630` -- displaced fracture of distal phalanx of right index finger**

                -   **`S62.630A` -- ... initial encounter for closed fracture**

                -   `S62.630B` -- ... initial encounter for open fracture

                -   `S62.630D` -- ... initial encounter for fracture with routine healing

### RxNorm

The NIH National Library of Medicine (NLM) produces [RxNorm](https://www.nlm.nih.gov/research/umls/rxnorm/index.html) and [summarizes its purpose](https://www.nlm.nih.gov/research/umls/rxnorm/index.html) as follows:

> RxNorm provides normalized names for clinical drugs and links its names to many of the drug vocabularies commonly used in pharmacy management and drug interaction software... By providing links between these vocabularies, RxNorm can mediate messages between systems not using the same software and vocabulary.

Its scope includes the names of prescription and many over-the-counter drugs approved for use in the US, including generic and branded medications. RxNorm does not cover bulk powders, food, dietary supplements, and medical devices.

#### Structure

NLM completes the following three steps when classifying a drug [@rx_norm_nih]:

1.  **Group source data**: When NLM receives drug names with different formats that refer to the same medication, it groups them all together and refers to them as **synonyms**. This group of synonyms is called a **concept**. Below are examples of different synonyms that all refer to the same concept:
    -   Naproxen Tab 250 MG

    -   Naproxen 250mg tablet (product)

    -   NAPROXEN\@250 mg\@ORAL\@TABLET

    -   Naproxen 250 MILLIGRAM In 1 TABLET ORAL TABLET

    -   NAPROXEN 250MG TAB,UD \[VA Product\]
2.  **Create normalized name for a concept**: After synonyms are grouped into a concept, RxNorm then creates a normalized name for it detailing the ingredient, strength, and dose form. If the drug is branded or in a pack, then those are also included. For the concept above, the RxNorm normalized name is "Naproxen 250 MG Oral Tablet." The branded version is "Naproxen 250 MG Oral Tablet \[Prosaid\]." The general format for an RxNorm normalized name is dependent on two factors: (1) generic vs. branded, and (2) single vs. pack. Below summarizes the general formats for each scenario:
    -   Generic drugs - Ingredient Strength Dose Form

    -   Branded drugs - Ingredient Strength Dose Form \[Brand Name\]

    -   Generic drug packs - {# (Ingredient Strength Dose Form) / \# (Ingredient Strength Dose Form)} Pack

    -   Branded drug packs - {# (Ingredient Strength Dose Form) / \# (Ingredient Strength Dose Form)} Pack \[Brand Name\]
3.  **Assign concept unique identifier (RXCUI)**: The RXCUI is a numeric identifier that is a code assigned to a given concept. For example, the RXCUI for the above concept example is `198013`.

RxNorm normalized names can have different levels of specificity, defined by the **term type (TTY)**. For example, depending on the TTY, an RxNorm normalized name might only include the ingredient, might only include the dose form, or one of many combinations of descriptors.

::: {.callout-caution collapse="true"}
## Expand to view the different TTYs

| TTY  | Name                              | Description                                                                                                                                                                                        | Example                                                                                                                                                                                                |
|:-----|:----------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| IN   | Ingredient                        | A compound or moiety that gives the drug its distinctive clinical properties. Ingredients generally use the United States Adopted Name (USAN).                                                     | Fluoxetine                                                                                                                                                                                             |
| PIN  | Precise Ingredient                | A specified form of the ingredient that may or may not be clinically active. Most precise ingredients are salt or isomer forms.                                                                    | Fluoxetine Hydrochloride                                                                                                                                                                               |
| MIN  | Multiple Ingredients              | Two or more ingredients appearing together in a single drug preparation, created from SCDF. In rare cases when IN/PIN or PIN/PIN combinations of the same base ingredient exist, created from SCD. | Fluoxetine / Olanzapine                                                                                                                                                                                |
| DF   | Dose Form                         | See [Appendix 2](https://www.nlm.nih.gov/research/umls/rxnorm/docs/2018/appendix2.html) for a full list of Dose Forms.                                                                             | Oral Solution                                                                                                                                                                                          |
| DFG  | Dose Form Group                   | See [Appendix 3](https://www.nlm.nih.gov/research/umls/rxnorm/docs/2018/appendix3.html) for a full list of Dose Form Groups.                                                                       | Oral Liquid                                                                                                                                                                                            |
| SCDC | Semantic Clinical Drug Component  | Ingredient + Strength                                                                                                                                                                              | Fluoxetine 4 MG/ML                                                                                                                                                                                     |
| SCDF | Semantic Clinical Drug Form       | Ingredient + Dose Form                                                                                                                                                                             | Fluoxetine Oral Solution                                                                                                                                                                               |
| SCDG | Semantic Clinical Dose Form Group | Ingredient + Dose Form Group                                                                                                                                                                       | Fluoxetine Oral Product                                                                                                                                                                                |
| SCD  | Semantic Clinical Drug            | Ingredient + Strength + Dose Form                                                                                                                                                                  | Fluoxetine 4 MG/ML Oral Solution                                                                                                                                                                       |
| BN   | Brand Name                        | A proprietary name for a family of products containing a specific active ingredient.                                                                                                               | Prozac                                                                                                                                                                                                 |
| SBDC | Semantic Branded Drug Component   | Ingredient + Strength + Brand Name                                                                                                                                                                 | Fluoxetine 4 MG/ML \[Prozac\]                                                                                                                                                                          |
| SBDF | Semantic Branded Drug Form        | Ingredient + Dose Form + Brand Name                                                                                                                                                                | Fluoxetine Oral Solution \[Prozac\]                                                                                                                                                                    |
| SBDG | Semantic Branded Dose Form Group  | Brand Name + Dose Form Group                                                                                                                                                                       | Prozac Pill                                                                                                                                                                                            |
| SBD  | Semantic Branded Drug             | Ingredient + Strength + Dose Form + Brand Name                                                                                                                                                     | Fluoxetine 4 MG/ML Oral Solution \[Prozac\]                                                                                                                                                            |
| PSN  | Prescribable Name                 | Synonym of another TTY, given for clarity and for display purposes in electronic prescribing applications. Only one PSN per concept.                                                               | Leena 28 Day Pack                                                                                                                                                                                      |
| SY   | Synonym                           | Synonym of another TTY, given for clarity.                                                                                                                                                         | Prozac 4 MG/ML Oral Solution                                                                                                                                                                           |
| TMSY | Tall Man Lettering Synonym        | Tall Man Lettering synonym of another TTY, given to distinguish between commonly confused drugs.                                                                                                   | FLUoxetine 10 MG Oral Capsule \[PROzac\]                                                                                                                                                               |
| BPCK | Brand Name Pack                   | {# (Ingredient Strength Dose Form) / \# (Ingredient Strength Dose Form)} Pack \[Brand Name\]                                                                                                       | {12 (Ethinyl Estradiol 0.035 MG / Norethindrone 0.5 MG Oral Tablet) / 9 (Ethinyl Estradiol 0.035 MG / Norethindrone 1 MG Oral Tablet) / 7 (Inert Ingredients 1 MG Oral Tablet) } Pack \[Leena 28 Day\] |
| GPCK | Generic Pack                      | {# (Ingredient + Strength + Dose Form) / \# (Ingredient + Strength + Dose Form)} Pack                                                                                                              | {11 (varenicline 0.5 MG Oral Tablet) / 42 (varenicline 1 MG Oral Tablet) } Pack                                                                                                                        |
:::

### CVX

[CVX](https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=cvx) is a standard terminology for both active and inactive vaccines in the US. It is developed and maintained by the CDC's National Center of Immunization and Respiratory Diseases (NCIRD). Inactive vaccine CVX codes allow for the analysis of historical immunization records. [@cvx]

Concepts in CVX are assigned a short numeric code (e.g., `207` for Moderna's initial COVID-19 vaccine). Each vaccine also has a short description, a full name, and a status (e.g. `Active` or `Inactive`).

CVX codes are also [mapped into groups](https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=vg) by disease targeted, and to [vaccine manufacturers](https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=tradename).

## Terminology in FHIR

There are three key FHIR resources for terminology:

+--------------------------------------------------------+-------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| FHIR Resource                                          | Description                                                                   | Example                                                                                                                                       | Potential research applications                                                                                                                  |
+========================================================+===============================================================================+===============================================================================================================================================+==================================================================================================================================================+
| [CodeSystem](https://www.hl7.org/fhir/codesystem.html) | Describes a code system, its concepts, and the codes identifying the concepts | The [LOINC code system](https://loinc.org/fhir/)                                                                                              | -   Identifying which code system a given code comes from                                                                                        |
|                                                        |                                                                               |                                                                                                                                               |                                                                                                                                                  |
|                                                        |                                                                               |                                                                                                                                               | -   Looking up the concept definition or other metadata associated with a given code                                                             |
|                                                        |                                                                               |                                                                                                                                               |                                                                                                                                                  |
|                                                        |                                                                               |                                                                                                                                               | -   Using concept relationship metadata to reason about or filter data                                                                           |
+--------------------------------------------------------+-------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| [ValueSet](https://www.hl7.org/fhir/valueset.html)     | Specifies a specific set of codes from code system(s)                         | [LOINC concepts identifying types of cancer staging systems](https://hl7.org/fhir/us/mcode/STU2/ValueSet-mcode-cancer-staging-system-vs.html) | -   Curating a list of concepts for use in a particular context                                                                                  |
|                                                        |                                                                               |                                                                                                                                               |                                                                                                                                                  |
|                                                        |                                                                               |                                                                                                                                               | -   Identifying a specific set of concepts from specific code systems allowed in a data element                                                  |
|                                                        |                                                                               |                                                                                                                                               |                                                                                                                                                  |
|                                                        |                                                                               |                                                                                                                                               | -   Validating that FHIR-formatted data have only the expected codes                                                                             |
+--------------------------------------------------------+-------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| [ConceptMap](https://www.hl7.org/fhir/conceptmap.html) | Identifies relationships between sets of concepts                             | [Mapping from SNOMED CT to ICD-10](https://www.hl7.org/fhir/R4B/conceptmap-103.html)                                                          | -   Creating mappings between two different code systems (e.g., mapping ICD-9 codes in historical records to ICD-10)                             |
|                                                        |                                                                               |                                                                                                                                               |                                                                                                                                                  |
|                                                        |                                                                               |                                                                                                                                               | -   Mapping a custom code system (e.g., custom diagnosis codes for a hospital) to a standardized code system for multi-hospital data aggregation |
+--------------------------------------------------------+-------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+

### CodeSystem resource details

The [CodeSystem FHIR resource](https://www.hl7.org/fhir/codesystem.html) defines an organized, managed collection of concepts that belong to a given terminology system. CodeSystems are used to computably represent properties of the standardized terminologies discussed above (like LOINC and ICD-10). These properties include:

-   The canonical identifier for the code system (typically a URL like `http://loinc.org` for LOINC, or an [OID](https://en.wikipedia.org/wiki/Object_identifier) (e.g., `2.16.840.1.113883.6.1` , which also [represents LOINC](https://loinc.org/oids/2.16.840.1.113883.6.1/))

-   Version

-   The concepts defined by the code system (i.e., a list of codes for concepts and their human-readable descriptions)

-   Publication metadata like a human-readable description, copyright information, and publication date

-   Some key properties of the code system itself, such as whether it exhibits concept permanence, whether it defines a [compositional grammar](https://www.hl7.org/fhir/R4B/codesystem-definitions.html#CodeSystem.compositional), and whether the codes that it defines are case sensitive

Here's an example of what an instance of a CodeSystem FHIR resource looks like:

``` json
{
  "resourceType" : "CodeSystem",
  "id" : "example",
  "meta" : {
    "profile" : ["http://hl7.org/fhir/StructureDefinition/shareablecodesystem"]
  },
  "text" : {
    "status" : "additional",
    "div" : "..."
  },
  "url" : "http://hl7.org/fhir/CodeSystem/example",
  "identifier" : [{
    "system" : "urn:ietf:rfc:3986",
    "value" : "urn:oid:2.16.840.1.113883.4.642.4.1827"
  },
  {
    "system" : "http://acme.com/identifiers/codesystems",
    "value" : "internal-cholesterol-inl"
  }],
  "version" : "5.0.0-cibuild",
  "name" : "ACMECholCodesBlood",
  "title" : "ACME Codes for Cholesterol in Serum/Plasma",
  "status" : "draft",
  "experimental" : true,
  "date" : "2016-01-28",
  "publisher" : "Acme Co",
  "contact" : [{
    "name" : "FHIR project team",
    "telecom" : [{
      "system" : "url",
      "value" : "http://hl7.org/fhir"
    }]
  }],
  "description" : "This is an example code system that includes all the ACME codes for serum/plasma cholesterol from v2.36.",
  "caseSensitive" : true,
  "content" : "complete",
  "filter" : [{
    "code" : "acme-plasma",
    "description" : "An internal filter used to select codes that are only used with plasma",
    "operator" : ["="],
    "value" : "the value of this filter is either 'true' or 'false'"
  }],
  "concept" : [{
    "code" : "chol-mmol",
    "display" : "SChol (mmol/L)",
    "definition" : "Serum Cholesterol, in mmol/L",
    "designation" : [{
      "use" : {
        "system" : "http://acme.com/config/fhir/codesystems/internal",
        "code" : "internal-label"
      },
      "value" : "From ACME POC Testing"
    }]
  },
  {
    "code" : "chol-mass",
    "display" : "SChol (mg/L)",
    "definition" : "Serum Cholesterol, in mg/L",
    "designation" : [{
      "use" : {
        "system" : "http://acme.com/config/fhir/codesystems/internal",
        "code" : "internal-label"
      },
      "value" : "From Paragon Labs"
    }]
  },
  {
    "code" : "chol",
    "display" : "SChol",
    "definition" : "Serum Cholesterol",
    "designation" : [{
      "use" : {
        "system" : "http://acme.com/config/fhir/codesystems/internal",
        "code" : "internal-label"
      },
      "value" : "Obdurate Labs uses this with both kinds of units..."
    }]
  }]
}
```

### ValueSet resource details

The [ValueSet FHIR resource](https://www.hl7.org/fhir/valueset.html) "specifies a set of codes drawn from one or more code systems, intended for use in a particular context." ValueSets don't refer directly to CodeSystems; rather, they [identify](https://www.hl7.org/fhir/valueset-definitions.html#ValueSet.compose.include.system) the relevant CodeSystem by its unique canonical URI.

Here's an example of what an instance of a ValueSet FHIR resource looks like:

::: {.callout-caution collapse="true"} \## Expand to view an example of a `ValueSet` FHIR Resource that specifies the value set of "All CPT Values" from the code system SNOMED CT

``` json
{
  "resourceType" : "ValueSet",
  "id" : "example-cpt-all",
  "text" : {
    "status" : "generated",
    "div" : "..."
  },
  "url" : "http://hl7.org/fhir/ValueSet/example-cpt-all",
  "identifier" : [{
    "system" : "urn:ietf:rfc:3986",
    "value" : "urn:oid:2.16.840.1.113883.4.642.3.3138"
  }],
  "version" : "5.0.0-cibuild",
  "name" : "AllCPTCodes",
  "title" : "All CPT codes",
  "status" : "active",
  "experimental" : true,
  "date" : "2015-03-12",
  "publisher" : "Health Level Seven International (Vocabulary)",
  "description" : "A value set that includes all CPT codes",
  "useContext" : [{
    "code" : {
      "system" : "http://example.org/fhir/CodeSystem/use-contexts",
      "code" : "species"
    },
    "valueCodeableConcept" : {
      "coding" : [{
        "system" : "http://snomed.info/sct",
        "code" : "337915000",
        "display" : "Homo sapiens (organism)"
      }]
    }
  }],
  "jurisdiction" : [{
    "coding" : [{
      "system" : "urn:iso:std:iso:3166",
      "code" : "US"
    }]
  }],
  "copyright" : "CPT Copyright © 2014 American Medical Association. All rights reserved.",
  "compose" : {
    "include" : [{
      "system" : "http://www.ama-assn.org/go/cpt"
    }]
  }
}
```

### ConceptMap

The [ConceptMap FHIR resource](https://www.hl7.org/fhir/conceptmap.html) provides a mapping from one set of concepts to other concepts. The example below maps SNOMED CT to ICD-10 using an instance of the ConceptMap resource:

::: {.callout-caution collapse="true"} \## Expand to view an example of a `ConceptMap` FHIR Resource that maps SNOMED CT to ICD-10

``` json
{
  "resourceType" : "ConceptMap",
  "id" : "103",
  "text" : {
    "status" : "extensions",
    "div" : "..."
  },
  "url" : "http://hl7.org/fhir/ConceptMap/103",
  "identifier" : [{
    "system" : "urn:ietf:rfc:3986",
    "value" : "urn:oid:2.16.840.1.113883.4.642.14.7"
  },
  {
    "system" : "urn:ietf:rfc:3986",
    "value" : "urn:uuid:53cd62ee-033e-414c-9f58-3ca97b5ffc3b"
  }],
  "version" : "5.0.0-cibuild",
  "name" : "SNOMEDCTToICD10CMMappingsForFractureOfUlna",
  "title" : "SNOMED CT to ICD-10-CM mappings for fracture of ulna",
  "status" : "draft",
  "experimental" : true,
  "date" : "2012-06-13",
  "publisher" : "HL7, Inc",
  "contact" : [{
    "name" : "FHIR project team (example)",
    "telecom" : [{
      "system" : "url",
      "value" : "http://hl7.org/fhir"
    }]
  }],
  "description" : "Example rule-based mappings between SNOMED CT to ICD-10-CM for fracture of ulna",
  "jurisdiction" : [{
    "coding" : [{
      "system" : "http://unstats.un.org/unsd/methods/m49/m49.htm",
      "code" : "840",
      "display" : "United States of America"
    }]
  }],
  "purpose" : "Show example rule based mappings",
  "copyright" : "Creative Commons 0",
  "sourceScopeCanonical" : "http://snomed.info/sct?fhir_vs",
  "group" : [{
    "source" : "http://snomed.info/sct",
    "target" : "http://hl7.org/fhir/sid/icd-10-cm",
    "element" : [{
      "code" : "263204007",
      "target" : [{
        "code" : "S52.209A",
        "relationship" : "source-is-broader-than-target",
        "comment" : "The target mapping to ICD-10-CM is 'source-is-broader-than-target', since additional patient data on the encounter (initial vs. subsequent) and fracture type is required for a valid ICD-10-CM mapping."
      }]
    },
    {
      "code" : "263204007",
      "target" : [{
        "code" : "S52.209D",
        "relationship" : "source-is-broader-than-target",
        "comment" : "The target mapping to ICD-10-CM is 'source-is-broader-than-target', since additional patient data on the encounter (initial vs. subsequent), fracture type and healing (for subsequent encounter) is required for a valid ICD-10-CM mapping."
      }]
    }]
  }]
}
```
