repos:
  - repo: local
    hooks:
      - id: spellcheck
        name: Spell check .qmd files
        entry: script/spellcheck-precommit.sh --files
        language: system
        files: \.qmd$
      - id: module-date-check
        name: Ensure module files have date in frontmatter
        entry: script/check-for-date-in-frontmatter.sh
        language: system
