#!/bin/bash

wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.433/quarto-1.3.433-linux-amd64.tar.gz
mkdir $RUNNER_WORKSPACE/opt
tar -C $RUNNER_WORKSPACE/opt -xvzf quarto-1.3.433-linux-amd64.tar.gz
mkdir $RUNNER_WORKSPACE/bin
ln -s $RUNNER_WORKSPACE/opt/quarto-1.3.433/bin/quarto $RUNNER_WORKSPACE/bin/quarto

export PATH="/$RUNNER_WORKSPACE/bin:$PATH"