---
title: Overview
sidebar: false
---

The **Overview** provides an introduction to FHIR for research, and details on two additional areas of general interest for researchers: SMART on FHIR and its research applications, and data modeling in FHIR.

Select your [role](/roles.html) to <mark>highlight</mark> the content that is most relevant to you:

<a href="#" class="btn-role" data-role="investigator">Investigator</a> <a href="#" class="btn-role" data-role="research-leader">Research Leader</a> <a href="#" class="btn-role" data-role="informaticist">Informaticist</a> <a href="#" class="btn-role" data-role="software-engineer">Software Engineer</a> <a href="#" class="btn-role" data-role="clinician-scientist">Clinician Scientist/Trainee</a>

## FHIR for Research

-   [FHIR from 10,000 Feet](/modules/fhir-from-10000-ft.qmd)
-   [FHIR from 1,000 Feet](/modules/fhir-from-1000-ft.qmd)
-   [Real-World Research Using FHIR](/modules/fhir-research.qmd)
-   [Brief History of FHIR](/modules/fhir-history.qmd)
-   [Terminology Introduction](/modules/terminology.qmd)
-   [Common Data Models & FHIR](/modules/cdms.qmd)
-   [The FHIR Community & Documentation](/modules/fhir-community.qmd)
-   [Key FHIR Resources](/modules/key-fhir-resources.qmd)
-   [Using the FHIR API to Access Data](/modules/fhir-accessing-data.qmd)
-   [Genomics Data Standardization with FHIR](/modules/genomics.qmd)
-   [Emerging Innovations](/modules/fhir-emerging-innovations.qmd)

Many of these topics are covered in [an introductory webinar](/webinars/intro/index.qmd).

## FHIR API Technologies

*Recommended: complete highlighted "FHIR for Research" modules for your role first*

### SMART on FHIR

-   [Introduction](/modules/new-smart-on-fhir-intro.qmd)
-   [Technical Details](/modules/new-smart-on-fhir-tech.qmd)
-   [Workshop](/workshops/smart-on-fhir/index.qmd)

### CDS Hooks

-   [Introduction](/modules/new-cds-hooks-intro.qmd)
-   [Types of CDS Hooks](/modules/new-cds-hooks-types.qmd)
-   [Technical Example](/modules/new-cds-hooks-tech.qmd)

### Other

-   [Bulk Data Access](/modules/new-bulk-fhir.qmd)

## Data Modeling in FHIR

*Recommended: complete highlighted "FHIR for Research" modules for your role first*

-   [Reading a FHIR specification](/modules/data-modeling-reading-igs.qmd)
-   [Real world FHIR specifications](/modules/data-modeling-real-world-igs.qmd)
-   [Writing a FHIR specification](/modules/data-modeling-writing-igs.qmd)

```{=html}
<script type="module">

const all_modules = document.querySelectorAll("section>ul>li");

/* select_modules(string)
 *   highlights modules corresponding to role via role_module_map
 *   param: string - role name in lower kebab case
 */
function select_modules(string) {
    // remove all highlights
    all_modules.forEach((li_node) => {
        var mark_node = li_node.firstChild;
        var a_node = mark_node.firstChild;

        if( mark_node.nodeName == "MARK" ) {
            li_node.removeChild(mark_node);
            li_node.appendChild(a_node);
        }
    });

    // add highlights based on role_module_map
    role_module_map.forEach((mapping) => {
        if( mapping.role == string ) {
            mapping.modules.forEach((interest_module) => {
                document.querySelectorAll(`li [href*="${interest_module.slug}"]`).forEach((interest_a_node) => {

                    //console.log("selecting module ", interest_a_node);

                    var interest_li_node = interest_a_node.parentNode;
                    var mark_node = document.createElement("mark");
                    interest_li_node.appendChild(mark_node);
                    mark_node.appendChild(interest_a_node);

                    //console.log("appended ", interest_a_node, " to ", mark_node);
                });
            });
            return;
        }
    })
}


/* Possible Roles:
 *   investigator
 *   research-leader
 *   informaticist
 *   software-engineer
 *   clinician-scientist
 */

/* select_role(role)
 *   clears any previous selected roles
 *   highlights the selected role
 *   sets the corresponding cookie
 */
function select_role(role) {
    store.setItem("role", role);

    document.querySelectorAll("[data-role]").forEach((a_node) => {
        a_node.classList.remove("btn", "btn-sm", "btn-secondary", "fw-bold", "rounded");
        a_node.classList.add("btn-role");
    });

    var selected_a_node = document.querySelector(`[data-role="${role}"]`);
    selected_a_node.classList.add("btn", "btn-sm", "btn-secondary", "fw-bold", "rounded");
    selected_a_node.classList.remove("btn-role");
}


// trigger role selection on clicking <a data-role=...>
document.querySelectorAll("a[data-role]").forEach((role_link) => {
    role_link.addEventListener("click", (e) => {
        var role = e.target.dataset.role;
        select_role(role);
        select_modules(role);
    });
});

// execute select_role and select_modules once to make sure the page is aligned with cookie
// or set cookie if it is unset
if( store.getItem("role") ) {
    select_role(store.getItem("role"));
    select_modules(store.getItem("role"));
}
else {
    const DEFAULT_ROLE = "research-leader";

    select_role(DEFAULT_ROLE);
    select_modules(DEFAULT_ROLE);
}

</script>
```
